# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import os
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd

df=pd.read_excel("excel.xlsx")
df_out=pd.DataFrame()
df_manage=pd.read_excel("manage.xlsx")


for k in range(len(df)):

  email=df.iloc[k,0]
  password=df.iloc[k,1]
  try:

    driver = webdriver.Chrome(os.getcwd() + '/chromedriver')
    driver.get("https://iqosphere.jp/login")
    time.sleep(3)
    driver.find_element_by_xpath('//*[@id="popup"]/section[1]/div/a').click()
    driver.find_element(By.NAME, "login_id").send_keys(email)
    driver.find_element(By.NAME, "password").send_keys(password)
    driver.find_element(By.NAME, "password").send_keys(Keys.ENTER)
    time.sleep(3)
    driver.get("https://iqosphere.jp/memberbenefits/myqoins/history/")
    time.sleep(8)
    driver.find_element_by_class_name('prizes').click()
    driver.find_element_by_class_name('prizes').click()
    for i in range(1,6):
      xpath='//*[@id="v4"]/div[4]/div[1]/div/div[1]/ul/li['+str(i)+']/section/div/p[2]/a'
      try:
        list = driver.find_element_by_xpath(xpath).get_attribute("href")
        list=list[list.find("param_code="):]
        list=list[:list.find("&")]
        list = list[list.find("=")+1:]
        df.iloc[k,8+i]=list
        if len(df_manage[df_manage["コード"] == list]) == 0:
          s = pd.Series([list, ""], index=df_manage.columns,name=len(df_manage)+1)
          df_manage=df_manage.append(s)

      except:
        pass
  except:
    pass
  driver.close()
df=df.set_index('メール')
df.to_excel('excel.xlsx')
df_manage=df_manage.set_index("コード")
df_manage.to_excel('manage.xlsx')

